import type { Metadata } from "next";
import "./globals.css";
import StateListContextProvider from "@/context/StateListProvider";
import StoreProvider from "@/redux/provider";
import BusinessInfoContextProvider from "@/context/BusinessInfoContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <BusinessInfoContextProvider>
            <StateListContextProvider>{children}</StateListContextProvider>
          </BusinessInfoContextProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
